[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Personal Asset Manager"
authors = [{name = "James", email = "james.lynch.uml@gmail.com"}]
dynamic = ["version", "description"]
